### ISSUE TITLE
KeyError: 'unknown name in torrent params: paused'

### ISSUE THREAD

**Issue by laar19** [danfolkes/Magnet2Torrent#31]
Hello, i would like to fork this project and make a good user interface, but first, when i try it, using the command line example that you provide, i get this error:

```
Traceback (most recent call last):
  File "Magnet_To_Torrent2.py", line 144, in <module>
    main()
  File "Magnet_To_Torrent2.py", line 140, in main
    magnet2torrent(magnet, output_name)
  File "Magnet_To_Torrent2.py", line 51, in magnet2torrent
    handle = lt.add_magnet_uri(ses, magnet, params)
KeyError: 'unknown name in torrent params: paused'
```

**Comment by booshnelli** [comment]
Yeah I can confirm that with **libtorrent-rasterbar10**, **libtorrent-rasterbar-dev**, and **python3-libtorrent** all installed, running `python3 Magnet_To_Torrent2.py -m (magnet) -o (output)` results in the aforementioned dump. At the very least, I believe the culprit is that the libtorrent function `add_magnet_uri` has been deprecated.

Here are some mentions to that being so:

- https://github.com/Flexget/Flexget/issues/2424
- https://onehack.us/t/transfer-error-from-torrent-to-gdrive-using-colab/173617
- https://gitlab.com/LazyLibrarian/LazyLibrarian/-/issues/2022

Probably not a big fix required to remedy. Haven't tried but perhaps rolling back to something like **libtorrent-rasterbar9** would suffice as a workaround? Anyway hope I could be of some help!
